install_yarn: &install_yarn
  run:
    name: Install Yarn
    command: |
      sudo apt-get update
      sudo apt-get install apt-transport-https
      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      sudo apt-get update
      sudo rm -f /usr/local/bin/yarn
      YARN_VERSION=$( jq -r '.engines.yarn | gsub("[^0-9.]";"")' < package.json )
      sudo apt-get install --no-install-recommends yarn=$YARN_VERSION-1

mkdir_results: &mkdir_results
  run:
    name: Create test result directory
    command: mkdir -p /tmp/test-results/code

install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: yarn --frozen-lockfile

run_tests: &run_tests
  run:
    name: Run tests
    command: yarn run test:ci

report_coverage: &report_coverage
  run:
    name: Report coverage
    command: yarn run coverage

store_test_results: &store_test_results
  store_test_results:
    path: /tmp/test-results
    when: always

store_artifacts: &store_artifacts
  store_artifacts:
      path: /tmp/test-results
      destination: test-results
      when: always

version: 2.0

jobs:
  node8:
    docker:
      - image: circleci/node:8-stretch
    working_directory: ~/code
    steps:
      - checkout
      - <<: *install_yarn
      - <<: *mkdir_results
      - restore_cache:
          keys:
            - v1-{{ arch }}-node8-dependencies-{{ checksum "yarn.lock" }}
            - v1-{{ arch }}-node8-dependencies-
      - <<: *install_dependencies
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-{{ arch }}-node8-dependencies-{{ checksum "yarn.lock" }}
      - <<: *run_tests
      - <<: *store_test_results
      - <<: *store_artifacts
  node10:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/code
    steps:
      - checkout
      - <<: *install_yarn
      - <<: *mkdir_results
      - restore_cache:
          keys:
            - v1-{{ arch }}-node10-dependencies-{{ checksum "yarn.lock" }}
            - v1-{{ arch }}-node10-dependencies-
      - <<: *install_dependencies
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-{{ arch }}-node10-dependencies-{{ checksum "yarn.lock" }}
      - <<: *run_tests
      - <<: *report_coverage
      - <<: *store_test_results
      - <<: *store_artifacts

workflows:
  version: 2
  build:
    jobs:
      - node8
      - node10
